### ISSUE TITLE
Crates.io outdated

### ISSUE THREAD

**Issue by attackgoat** [KalitaAlexey/bmfont-rust#9]
Hello!

Would it be possible to publish the latest version of this crate? The `master` branch contains the @mystal kerning fix which is not on crates.io yet.

Alternatively if you would rather add me as a maintainer I would be happy to handle this. I've been using this library for *years* and love it!

Thanks!

**Comment by KalitaAlexey** [comment]
Maintainer of the crate or the repo?

**Comment by KalitaAlexey** [comment]
I'm going to publish a new version after I updated the code. I did `cargo fmt` and `cargo check`.
However, now I see `cargo test` fails.
I found at least one bug with kernings.

**Comment by KalitaAlexey** [comment]
@attackgoat, Do you actually use it somewhere? I ran my example with "aou" and it looks bad.

**Comment by attackgoat** [comment]
I have an example in this repo:
https://github.com/attackgoat/screen-13
(follow instructions for the 'basic' example)

At least for the fonts I've tried this library has been completely perfect. I can't say what other fonts might do and I have not looked into the code too deeply. My code continues to compile/work when I change the dependency from the @mystal fork to your latest code.

When I replace your example text with aou I don't see the issue you mention.

**Comment by KalitaAlexey** [comment]
The first bug is with Rect::max_x and max_y. They have -1 and it crops the last pixel. I see you don't use it.

**Comment by KalitaAlexey** [comment]
0.3.1 is published.
